// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLPYK1JgVwvYZ4aoEiES6S4M9sq83tAU0',
    appId: '1:999853208663:web:dc7b0d919c8ba6deb89f12',
    messagingSenderId: '999853208663',
    projectId: 'rede-mais-app',
    authDomain: 'rede-mais-app.firebaseapp.com',
    storageBucket: 'rede-mais-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdOcmf_kNYC0aSG9UYlfXTT2UdEYdbdro',
    appId: '1:999853208663:android:f66dc1f9d903b19db89f12',
    messagingSenderId: '999853208663',
    projectId: 'rede-mais-app',
    storageBucket: 'rede-mais-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4zBDUoP-DfhTucFH6Fs-N-woqQzFZlw',
    appId: '1:999853208663:ios:bb22ab4edc01b9b8b89f12',
    messagingSenderId: '999853208663',
    projectId: 'rede-mais-app',
    storageBucket: 'rede-mais-app.firebasestorage.app',
    iosBundleId: 'com.example.redeMais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH4zBDUoP-DfhTucFH6Fs-N-woqQzFZlw',
    appId: '1:999853208663:ios:bb22ab4edc01b9b8b89f12',
    messagingSenderId: '999853208663',
    projectId: 'rede-mais-app',
    storageBucket: 'rede-mais-app.firebasestorage.app',
    iosBundleId: 'com.example.redeMais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLPYK1JgVwvYZ4aoEiES6S4M9sq83tAU0',
    appId: '1:999853208663:web:295c7bfa6a1222deb89f12',
    messagingSenderId: '999853208663',
    projectId: 'rede-mais-app',
    authDomain: 'rede-mais-app.firebaseapp.com',
    storageBucket: 'rede-mais-app.firebasestorage.app',
  );
}
